title: "Léon Habineza Portfolio"
description: "A detailed professional portfolio showcasing my work in research, project management, and public health."
author: "Léon Habineza"
email: "leonhabineza@gmail.com"
social:
  linkedin: "https://www.linkedin.com/in/leonhabineza"
  github: "https://github.com/leonhabineza"
  twitter: "https://twitter.com/leonhabineza"

# Navigation
navigation:
  - name: "About Me"
    link: "#about-me"
  - name: "Experience"
    link: "#professional-experience"
  - name: "Projects"
    link: "#projects"
  - name: "Skills"
    link: "#key-skills"
  - name: "Contact"
    link: "#contact"

# Projects
projects:
  - title: "Barriers to Health Services Access"
    organization: "Swiss TPH"
    year: 2019
    description: "Fieldwork coordination, participant recruitment, and data analysis."
  - title: "Nutrition Project"
    organization: "Swiss TPH"
    year: 2018
    description: "Transcription and translation for nutrition-focused studies."
  - title: "Monitoring Annual Results"
    organization: "Food for the Hungry"
    year: 2021
    description: "Oversight of enumerators and data collection protocols."
  - title: "Positive Masculinity for SRHR"
    organization: "RWAMREC"
    year: 2020–2021
    description: "Team coordination and logistics for gender equality studies."
  - title: "Barrier to School Return After COVID-19"
    organization: "Amplify"
    year: 2020
    description: "Support for transcription and translation in education research."
